# Generated by Django 4.2.7 on 2025-03-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_branch_remove_guest_to_see_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='to_see',
        ),
    ]
