# Generated by Django 4.2.7 on 2025-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_alter_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='to_see',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
